random-server: random-test-server.c
	gcc random-test-server.c -o random-test-server -lmodbus -I/usr/include/modbus

random-client: random-test-client.c
	gcc random-test-client.c -o random-test-client -lmodbus -I/usr/include/modbus